### ISSUE TITLE
sys.meta_path 调用顺序?

### ISSUE THREAD

**Issue by neo1218** [Liuchang0812/slides#2]
文章里说:

> 在Python查找的时候，如果在sys.modules没有查找到，就会依次调用sys.meta_path中的finder对象

而[PEP302](https://www.python.org/dev/peps/pep-0302/#specification-part-2-registering-hooks)里面说到:

> Meta hooks are called at the start of import processing, before any other import processing 

这里的meta hooks不就是sys.meta_path中的finder对象吗?

![2016-08-06 11 13 55](https://cloud.githubusercontent.com/assets/10671733/17454412/e7edf3ae-5bc6-11e6-9822-633b23253405.png)
不过我在解释器试了一下, 确实在调用finder对象前会先加载已经存在于sys.modules中的模块.

那么pep中"before any other import processing" 不就有问题了吗?

谢谢!

**Comment by ficapy** [comment]
https://docs.python.org/3.5/reference/import.html?highlight=import%20hooks
文档后面跟的一句是`Meta hooks are called at the start of import processing, before any other import processing has occurred, other than sys.modules cache look up`，除了sys.modules缓存查找
